/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.lang.reflect.Method;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author estudiantes
 */
@SuppressWarnings("serial")
public class VistaSplash extends JFrame {

    private final Modelo sistema;

    /**
     * Creates new form VistaSplash
     */
    public VistaSplash(Modelo modelo) {
        sistema = modelo;
        initComponents();
        hacerTransparente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSplashInicio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().add(lblSplashInicio, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblSplashInicio;
    // End of variables declaration//GEN-END:variables
    private void hacerTransparente() {
        try {
            @SuppressWarnings("rawtypes")
            Class clazz = Class.forName("com.sun.awt.AWTUtilities");
            @SuppressWarnings("unchecked")
            Method method = clazz.getMethod("setWindowOpaque", java.awt.Window.class, Boolean.TYPE);
            method.invoke(clazz, this, false);            
        } catch (Exception e) {
        }
        lblSplashInicio.setIcon(new ImageIcon(sistema.getImgFondo()));
    }

    
}
